# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Build
      run: go build -o teAction src/main.go

    - uses: actions/upload-artifact@v3
      with:
        name: teAction-artifact
        path: teAction

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - uses: actions/download-artifact@v3
      with:
        name: teAction-artifact
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: run
      #run: ./teAction
      run: go run src/main.go
